### ISSUE TITLE
前端登录403错误，跨域问题

### ISSUE THREAD

**Issue by Omoinemie** [zfile-dev/zfile-vue#65]
前端地址：https://yun.vomiku.com
后端地址：https://rt.vomiku.com:7443
错误信息：
`login:1 
       GET https://yun.vomiku.com/login 404
login:1 
       Access to XMLHttpRequest at 'https://api.webtest.net/webspeeds' from origin 'https://yun.vomiku.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
webspeed.js:7001 
       POST https://api.webtest.net/webspeeds net::ERR_FAILED`

### nodejs 版本

TODO

(推荐使用 `v16` 以上)

<br />

### 包管理器及其版本 

TODO

(推荐使用 `pnpm`)

<br />

### 系统

TODO

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

TODO

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by zhaojun1998** [comment]
@Omoinemie 

前端页面是 vue history 模式，需要 nginx 做特殊配置，参考：https://blog.csdn.net/weixin_46034375/article/details/123821015

**Comment by Omoinemie** [comment]
js文件延迟好高啊，是什么原因啊
![Uploading image.png…]()

**Comment by zhaojun1998** [comment]
@Omoinemie 

这个自行排查吧，可尝试使用 http2 多路复用或上 cdn 等方案解决。

**Comment by Omoinemie** [comment]
我用Windows运行jar本地访问延迟也是70多毫秒
![image](https://user-images.githubusercontent.com/31991443/184892323-446687ee-0a43-4873-9a5a-feacb9c087d9.png)

**Comment by zhaojun1998** [comment]
欢迎提出优化方案，欢迎 PR
