### ISSUE TITLE
播放视频时调用本地potplayer播放生成的url多了字符25导致播放链接错误

### ISSUE THREAD

**Issue by yjm2018** [zfile-dev/zfile-vue#72]
![image](https://user-images.githubusercontent.com/43918760/217498746-6af33712-f22a-43b3-b122-e1fc0713af56.png)
使用网页播放的链接为：.../pd/gj/%E9%A3%8E%E7%AD%9D-2017/01.mp4
生成的potplayer播放链接为：.../pd/gj/%25E9%25A3%258E%25E7%25AD%259D-2017/01.mp4
可以看到多了两个25，导致后台解析失败

**Comment by zhaojun1998** [comment]
@yjm2018 

我测试了下，和你同样的目录，同样的文件名。不知道你的存储策略时什么，我的这个存储策略是本地存储。

你可以去试试：[https://demo.zfile.vip/gj/风筝-2017](https://demo.zfile.vip/gj/%E9%A3%8E%E7%AD%9D-2017)

播放地址为： [https://demo.zfile.vip/pd/gj/%E9%A3%8E%E7%AD%9D-2017/01.mp4](https://demo.zfile.vip/pd/gj/%E9%A3%8E%E7%AD%9D-2017/01.mp4)
调用 potplayer 地址为（可直接复制到浏览器回车调用）：[potplayer://https://demo.zfile.vip/pd/gj/%25E9%25A3%258E%25E7%25AD%259D-2017/01.mp4](potplayer://https://demo.zfile.vip/pd/gj/%25E9%25A3%258E%25E7%25AD%259D-2017/01.mp4)

我的 ZFile 版本是: `4.1.4`
PotPlayer 版本为: `20220706(1.7.21765)`

**Comment by zhaojun1998** [comment]
请先确定是否可在 ZFile 中在线播放，如果 ZFile 中也无法播放，那可能视频的编码不是 H.264 的

**Comment by yjm2018** [comment]
zfile在线可以播放，就是调用本地potplayer播放时不能播放，我通过后台debug发现zfile在线播放的地址和调用potplayer的地址不一样，猜测应该是前端生成的链接地址有问题吧。
直接复制zfile在线播放的地址到potplayer中就能正常播放。
我看你的回复中，测试的同我的问题一样。

我的zfile版本为4.1.3

**Comment by zhaojun1998** [comment]
@yjm2018 

没明白，我的演示站，你也是调用 potplayer 无法播放吗？

地址确实不一样啊，我上面给出示例了，调用 potplayer 的地址是二次编码的。

**Comment by yjm2018** [comment]
对的，使用你的示例调用我本地的potplayer也是无法播放的。你那里测试能播放吗？

**Comment by zhaojun1998** [comment]
@yjm2018 
我这里是可以播放的，就是演示站，请检查你的 potplayer 版本，我前面已经给出了我的版本。还有请说明你使用的操作系统，浏览器类型，浏览器版本

**Comment by yjm2018** [comment]
![image](https://user-images.githubusercontent.com/43918760/217561457-9957879f-44a5-4759-ad41-10d8469d925c.png)
![image](https://user-images.githubusercontent.com/43918760/217561565-45c4b8f6-8bf3-4209-b810-b789e2ebffa2.png)
![image](https://user-images.githubusercontent.com/43918760/217561643-d6912855-8a09-4a73-909b-ef9ea8512c88.png)
测试不行，哭

Windows11
chrome 110.0.5481.78（正式版本） （64 位）

**Comment by zhaojun1998** [comment]
我知道问题了，最新版的 potplayer 反而不支持二次编码了。旧版的支持。

我下版本更新会修复此问题。

**Comment by yjm2018** [comment]
好的，感谢
